steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/thienco-bot', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'thienco-bot',
           '--image', 'gcr.io/$PROJECT_ID/thienco-bot',
           '--region', 'asia-southeast1',
           '--allow-unauthenticated',
           '--set-env-vars',
           'ENV=prod,TELEGRAM_TOKEN=xxx,TELEGRAM_SECRET_TOKEN=yyy,LLM_API_KEY=sk-...,LLM_MODEL=meta-llama/llama-3.1-8b-instruct:free,LLM_BASE_URL=https://openrouter.ai/api,LLM_PROVIDER=openrouter,MAX_TOKENS=512,TEMPERATURE=0.3,MAX_CONTEXT_TOKENS=2000,SUPABASE_URL=...,SUPABASE_SERVICE_ROLE_KEY=...']
timeout: 900s
